// <auto-generated />
using Informational_system_Lib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Informational_system_Lib.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20210207133458_addCategoryToDatabase")]
    partial class addCategoryToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Informational_system_Lib.Models.Book", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Avtor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Janr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kolichestvo")
                        .HasColumnType("int");

                    b.Property<string>("Zaglavie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBook");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
